Feat/page ville
betagouv/france-chaleur-urbaine pull request #586
Opened 2023-09-25 12:09 UTC by cspriet

2023-09-25 12:33 UTC, desoindx requested changes

2023-09-25 12:33 UTC, desoindx commented on src/components/Cities/City.styles.ts
> +
C'est quoi ces noms de classe ?

2023-09-25 12:33 UTC, desoindx commented on src/components/Cities/City.tsx
> +};
Ca aurait été plus efficace d'avoir  villesData qui est un object avec le nom de la ville en minuscule comme clé et de faire villesData[city.toLowerCase()]

2023-09-25 12:33 UTC, desoindx commented on src/components/Cities/City.tsx
> +  const { suggestionService } = useServices();
```suggestion
  const { heatNetworkService, suggestionService} = useServices();
  const [cityCoord, setCityCoord] = useState<[number, number]>();
```

2023-09-25 12:33 UTC, desoindx commented on src/components/Cities/City.tsx
> +  );
Ca serait mieux de les hardcoder dans le villesdata

2023-09-25 12:33 UTC, desoindx commented on src/components/Cities/City.tsx
> +            <div className="column-video-guide">
utilise des StyledComponent directement

2023-09-25 12:33 UTC, desoindx commented on src/components/Cities/City.tsx
> +                  <MarkdownWrapper
C'est bizarre qu'on est la même vidéo avec un sous titre different
pareil mettre ce sous titre specifique dans les villesdata

2023-09-25 12:33 UTC, desoindx commented on src/components/Cities/City.tsx
> +                  <Button
C'est pas un bouton, c'est un lien !

2023-09-25 12:33 UTC, desoindx commented on src/components/Cities/City.tsx
> +        ''
ternaire inutile si c'est pour rien afficher tu peux utiliser &&

2023-09-25 12:33 UTC, desoindx commented on src/components/Cities/City.styles.ts
> +`;
Bizarre, il faudrait mieux un Title qui est directement un h2 et un subtilite qui est un h3

2023-09-25 12:33 UTC, desoindx commented on src/components/Cities/Dispositifs.tsx
> +                      target={dispositif.link.target}
rajouter des rel noopener et noreferer si t'es en blank

2023-09-25 12:33 UTC, desoindx commented on src/components/Cities/Dispositifs.tsx
> +                  <Title>
j'imagine que c'est un soucis de design figma, mais ca fait deux niveaux differents avec un h3

2023-09-25 12:33 UTC, desoindx commented on src/components/Cities/Header.tsx
> +          <div>
Useless div ?

2023-09-25 12:33 UTC, desoindx commented on src/components/Cities/Networks.tsx
> +  cityCoord?: [number, number];
comment cityCoord peut etre null ?

2023-09-25 12:33 UTC, desoindx commented on src/data/villes/index.js
> +export { default as userExperience } from './user-experience';
n'utilse pas de fichier index pour re exporter
attention au mix francais/anglais

2023-09-25 12:33 UTC, desoindx commented on src/components/Cities/City.tsx
> +        await heatNetworkService.findByIdentifiant(identifiant);
Ca m'embete qu'on soit obligé de recuperer le réseaux dans la db... normalement c'est des valeurs qui vont pas changer (a confirmer par Florence), on alourdit le chargement de la page pour rien

2023-09-25 12:33 UTC, desoindx commented on src/data/villes/villes.js
> +      src: '/img/banner_ville_lyon.jpg',
On pourrait pas se dire que la banner c'est toujours /img/banner_ville_${city}.jpg et eviter ce champs ?

2023-09-25 12:33 UTC, desoindx commented on src/pages/api/map/network.ts
> +//import { getCityElibilityStatus } from '@core/infrastructure/repository/addresseInformation';
to remove

2023-09-25 12:33 UTC, desoindx commented on src/pages/api/map/network.ts
> +//import { CityNetwork } from 'src/types/HeatNetworksResponse';
to remove

2023-09-25 12:41 UTC, cspriet commented on src/data/villes/villes.js
> +      src: '/img/banner_ville_lyon.jpg',
Si effectivement

2023-09-25 13:31 UTC, cspriet commented on src/components/Cities/City.styles.ts
> +
Ce sont les classes auto, j'étais persuadée de les avoir vu utilisées mais effectivement c'est pas clair du tout. J'ai fait le changement

2023-09-26 13:09 UTC, cspriet commented on src/components/Cities/Networks.tsx
> +  cityCoord?: [number, number];
Au début quand le calcul n'est pas encore fait. Mais du coup si je le mets en dur ce ne sera plus le cas.

2023-09-26 14:12 UTC, cspriet commented on src/components/Cities/City.tsx
> +                  <Button
C'est à dire ? 
Sur le figma c'est un bouton, comme j'ai réutilisé le même que sur la page copro j'ai fait un nouveau composant.

2023-09-26 14:50 UTC, cspriet commented on src/components/Cities/City.tsx
> +        await heatNetworkService.findByIdentifiant(identifiant);
Il y a le graph à afficher, ou alors il faut mettre toutes les valeurs nécessaires en dur.

2023-09-26 14:59 UTC, cspriet commented on src/data/villes/index.js
> +export { default as userExperience } from './user-experience';
J'avais mis en français le nom des villes car sur beaucoup d'autres les data sont en français. Je change ;)
Et pour l'export, je suis pas sûre de comprendre

2023-10-02 08:22 UTC, desoindx requested changes

2023-10-02 08:22 UTC, desoindx commented on src/components/Cities/City.tsx
> +      if (!network) getNetworkFromDB(cityData.networksData.identifiant);
```suggestion
      if (!network) {
        getNetworkFromDB(cityData.networksData.identifiant);
      }
```

2023-10-02 08:22 UTC, desoindx commented on src/components/Cities/City.tsx
> +                {city == 'strasbourg' ? 'sur ' : 'à '}
```suggestion
                {city === 'strasbourg' ? 'sur ' : 'à '}
```

2023-10-02 08:22 UTC, desoindx commented on src/components/Cities/City.tsx
> +                {city == 'strasbourg' ? 'sur ' : 'à '}
bizarre ce if non ? poruquoi seulement strasbourg ?

2023-10-02 08:22 UTC, desoindx commented on src/components/Cities/City.tsx
> +              {city == 'paris' && (
```suggestion
              {city === 'paris' && (
```

2023-10-02 08:22 UTC, desoindx commented on src/components/Cities/ClassedNetworks.tsx
> +      if (city == 'metz') kw = '30';
```suggestion
      if (city === 'metz') {
        kw = '30';
      }
```

2023-10-02 08:22 UTC, desoindx commented on src/components/Cities/ClassedNetworks.tsx
> +      let kw = `100`;
const kw = city === 'metz' ? '30' : '100'

2023-10-02 08:22 UTC, desoindx commented on src/components/Coproprietaire/CoproGuide.tsx
> +          <Link
Il faut mettre un event matomo pour ce bouton

2023-10-02 08:22 UTC, desoindx commented on src/components/Coproprietaire/CoproGuide.tsx
> +            target="_blank"
manque la rel

2023-10-02 08:22 UTC, desoindx commented on src/components/Coproprietaire/CoproGuide.tsx
> +      <div>
extra div ?

2023-10-02 08:31 UTC, cspriet commented on src/components/Cities/City.tsx
> +                {city == 'strasbourg' ? 'sur ' : 'à '}
Parce que le nom de la métropole c'est "l'Eurométropole de Strasbourg" le "à" ne passe pas...

2023-10-02 09:01 UTC, cspriet commented on src/components/Coproprietaire/CoproGuide.tsx
> +      <div>
Non, j'ai repris l'affichage tel qu'il était pour la page copro et quand je l'enlève plus rien n'est aligné donc je l'ai laissé. C'est mieux si je fais un styled component même vide ?

2023-10-02 09:35 UTC, desoindx approved these changes

2023-10-02 09:45 UTC, merged