Fix/networks
betagouv/france-chaleur-urbaine pull request #604
Opened 2023-10-09 14:30 UTC by cspriet

2023-10-09 15:36 UTC, desoindx requested changes

2023-10-09 15:36 UTC, desoindx commented on src/components/Network/EnergiesChart.tsx
> +    if (window.innerWidth >= 992) {
Ca va pas marcher au resize ca...

2023-10-09 15:39 UTC, cspriet commented on src/components/Network/EnergiesChart.tsx
> +    if (window.innerWidth >= 992) {
J'ai fait des tests mais les options de graph ont l'air statiques. Ça ne se met à jour qu'au rechargement. J'avais ajouté un event au resize et je l'ai donc enlevé pour ne pas en avoir d'inutile. Mais je peux le remettre pour qu'on teste un peu plus si tu veux ?

2023-10-09 16:02 UTC, cspriet commented on src/components/Network/EnergiesChart.tsx
> +    if (window.innerWidth >= 992) {
Bon désolée en fait c'est une erreur de ma part, j'ai fait tellement de test pour solutionner ça différemment... Mais le resize fonctionne bien !
J'en profite pour ajouter des modifs de Florence

2023-10-10 07:10 UTC, desoindx commented on src/components/Network/EnergiesChart.tsx
> +    console.log(window.innerWidth);
Extra console log

2023-10-10 10:17 UTC, merged