feat: add a black border to the map iframe
betagouv/france-chaleur-urbaine pull request #629
Opened 2023-11-15 16:20 UTC by totakoko

Pour théoriquement arriver à :
![image](https://github.com/betagouv/france-chaleur-urbaine/assets/8938024/35c6a2ca-f943-44d9-85f9-1a612bc2edfe)

2023-11-15 16:41 UTC, cspriet requested changes
Pour les iframes, on a aussi 
- /carte-collectivite
- /charleville-mezieres
- /dalkia
- /engie
- /viaseva
L'idéal serait d'ajouter une props au composant Map, comme ça si un jour ou l'autre on a une demande sans bordure, on est prêt.

2023-11-15 17:06 UTC, totakoko commented
> Pour les iframes, on a aussi
> 
> * /carte-collectivite
> * /charleville-mezieres
> * /dalkia
> * /engie
> * /viaseva
>   L'idéal serait d'ajouter une props au composant Map, comme ça si un jour ou l'autre on a une demande sans bordure, on est prêt.

J'ai fait les modifs, avec en plus la page `map`, qui est censée être intégrée dans une iframe... mais ce n'est peut-être pas une bonne idée. :D

2023-11-16 08:16 UTC, cspriet approved these changes

2023-11-16 09:13 UTC, totakoko commented
Changement de couleur suite au retour de Florence. Je merge !

2023-11-16 09:13 UTC, merged