feat: nouvelle page collectivites exploitants  WIP
betagouv/france-chaleur-urbaine pull request #631
Opened 2023-11-20 17:57 UTC by totakoko

2023-11-30 10:11 UTC, cspriet requested changes

2023-11-30 10:11 UTC, cspriet commented on src/pages/collectivites-et-exploitants.tsx
> +              <ButtonLink href="documentation/FCU_guide_collectivites.pdf">
Il manque de quoi traquer sur Matomo non ?

2023-11-30 10:11 UTC, cspriet commented on src/pages/collectivites-et-exploitants.tsx
> +              <ButtonLink href="documentation/FCU_guide_exploitants.pdf">
Ici aussi je crois qu'on traque sur Matomo

2023-11-30 10:11 UTC, cspriet commented on src/pages/collectivites-et-exploitants.tsx
> +                    marginTop: '20px',
On essaie de rester en base 8 pour les marges et padding. Donc plutôt 24px.
En règle générale sur les margin et padding tu peux utiliser les classes du DSFR

2023-11-30 10:11 UTC, cspriet commented on src/pages/collectivites-et-exploitants.tsx
> +                    color: '#000074',
Le h4 dans un fichier style externe par exemple ce serait vraiment plus clair. Là il y a plusieurs fois la même définition de style. En maintenance ce sera la galère si on doit changer un truc

2023-11-30 11:54 UTC, totakoko reviewed
Merci pour tes retours ! Je vais les prendre en compte et je te ping quand c'est bon. :)

2023-11-30 11:54 UTC, totakoko commented on src/pages/collectivites-et-exploitants.tsx
> +                    marginTop: '20px',
Ok, transformé en `fr-mt-3w` pour rester en base 8.
Je vais changer le reste des marges aussi et les arrondir quand nécessaire.

2023-11-30 11:54 UTC, totakoko commented on src/components/Ressources/Understanding.styles.ts
Oui, c'était pour centrer les tuiles horizontalement pour être un peu plus raccord avec la maquette (et joli selon moi).
Les 3 autres pages qui utilisent ce composant utilisent 4 tuiles, donc le problème apparaît moins.
Je peux revert le changement si tu veux.

2023-11-30 11:54 UTC, totakoko commented on src/components/Partners/Partners.tsx
Pour cette page en tout cas, c'est complètement voulu qu'on change le lien.
Je suppose que ce n'est pas gênant  pour les autres pages qui utilisent ce même composant.

2023-11-30 11:54 UTC, totakoko commented on src/components/IFrame/Map/IFrameMapIntegrationForm.tsx
Je vais externaliser tout le CSS inline en styled components pour rester cohérent avec l'existant. :+1:

2023-11-30 11:54 UTC, totakoko commented on src/pages/collectivites-et-exploitants.tsx
> +                    color: '#000074',
Je vais changer tout ça en styled components !

2023-11-30 17:44 UTC, cspriet approved these changes

2023-12-11 10:57 UTC, merged

2023-12-11 10:58 UTC, totakoko commented
Il restera le tracking sur les 2 guides dans une PR ultérieure.