Force light mode
betagouv/france-chaleur-urbaine pull request #840
Opened 2024-07-26 09:20 UTC by cspriet

2024-07-26 09:48 UTC, totakoko approved these changes
Pas pu tester chez moi, le mode sombre n'est pas reconnu par les sites donc tant pis !

2024-07-30 06:31 UTC, martinratinaud requested changes
Je viens de tester en local et je ne suis pas passé en light mode automatiquement.

De manière très bizarre, ma seule option pour passer en light mode a été de changer dans le panel "Elements" de chrome l'attribut `data-fr-scheme` de "dark" à "light"
Une fois cela fait et la page rechargée, je suis bien en light mode.

Mais si je rechange à "dark", ça garde cette config en mémoire

J'ai vérifié et je n'ai trouvé aucune variable
- dans les cookies
- dans le local storage

Donc je ne comprends pas bien d'où vient ce comportement mais il existe.

Si c'est le cas sur ta machine aussi, cela veut dire qu'on ne peut pas garantir que le site est en light mode et il faudrait donc revoir cela.

Si ce comportement n'est que sur ma machine, on peut déployer je pense.

A dispo pour en parler

2024-08-02 07:53 UTC, totakoko commented
> Je viens de tester en local et je ne suis pas passé en light mode automatiquement.
> 
> De manière très bizarre, ma seule option pour passer en light mode a été de changer dans le panel "Elements" de chrome l'attribut `data-fr-scheme` de "dark" à "light" Une fois cela fait et la page rechargée, je suis bien en light mode.
> 
> Mais si je rechange à "dark", ça garde cette config en mémoire
> 
> J'ai vérifié et je n'ai trouvé aucune variable
> 
> * dans les cookies
> * dans le local storage
> 
> Donc je ne comprends pas bien d'où vient ce comportement mais il existe.
> 
> Si c'est le cas sur ta machine aussi, cela veut dire qu'on ne peut pas garantir que le site est en light mode et il faudrait donc revoir cela.
> 
> Si ce comportement n'est que sur ma machine, on peut déployer je pense.
> 
> A dispo pour en parler

Je me rappelle que j'avais vu avec Clémence que le mode était stocké dans le local storage sous la clé `scheme` qui vaut soir dark soit light.
Tu dois avoir la valeur dark chez toi.
Je ne comprends pas pourquoi le DSFR ou la lib react a besoin de stocker cette information... mais ça veut dire que si on veut revenir au light mode pour tout le monde... il va falloir écrire une migration côté UI pour supprimer ce paramètre...
On en rediscute la semaine prochaine !

2024-08-07 14:14 UTC, cspriet commented
@totakoko @martinratinaud j'ai fait du forcing sur la balise HTML et j'ai enlevé le getColorSchemeHtmlAttributes, vous en pensez quoi ? 
J'ai moi ça fonctionne mais c'est peut-être pas très correct de faire ça comme ça.

2024-08-09 08:00 UTC, totakoko approved these changes

2024-08-09 08:00 UTC, totakoko commented on src/pages/_document.tsx
> +      <Html lang="fr" data-fr-scheme="light" prefix="og: http://ogp.me/ns#">
[Côté lib react-dsfr](https://github.com/codegouvfr/react-dsfr/blob/8c60c0a9f5562a960ef84cfc0be141aa5983d1a2/src/useIsDark/client.ts#L190C6-L192), la lib s'occupe de définir cet attribut, mais commence par vérifier la valeur dans le localStorage.

[Côté lib dsfr](https://github.com/GouvernementFR/dsfr/blob/fe9d66b4ccaa7c3a3c0cb07eca69ddd6787965c4/src/scheme/script/scheme/scheme.js#L25-L48), on voit que la valeur du local storage prend le dessus par rapport à celle de l'attribut du tag html.


Donc au final, si qqn est allé sur FCU avec la nouvelle version et qu'il est en dark mode, alors il le restera pour toujours tant qu'on supprime pas la valeur dans le localStorage. Donc est-ce qu'il ne faudrait pas faire qqch pour supprimer cette clé (ou plutôt la forcer à light) ? Et dans ce cas juste passer `defaultColorScheme: 'light',`

2024-08-20 13:59 UTC, merged