Factorization du theme pour faciliter l'utilisation de media queries
betagouv/france-chaleur-urbaine pull request #841
Opened 2024-08-05 11:16 UTC by martinratinaud

Pour la création du simulateur qui aura besoin d'une interface adaptée sur mobile, cette PR facilite l'utilisation de media query CSS et aussi simplifie le code en regroupant ce qui a ttrait au design et au theme dans un seul dossier.

2024-08-05 12:04 UTC, totakoko requested changes
Ok pour le principe, mais les styles n'ont pas dû être bien appliqués. C'est comme s'il n'y avait plus que la version mobile.

2024-08-05 12:04 UTC, totakoko commented on src/components/ui/Box.tsx
> -  xs: '320',
Il y a un appel à `breakpoint="xs"` dans le code, qui risque de ne plus marcher car 320px n'existe plus.
Je viens de tester sur dev et je n'arrive pas à avoir une largeur aussi petite. Donc c'est pas grave. Mais ça veut dire que ce breakpoint peut être supprimé alors (avec la ResponsiveRow).

2024-08-05 12:04 UTC, totakoko commented on src/components/ui/Box.tsx
> +  ${({ theme, breakpoint }) => theme.media[breakpoint ?? 'lg']`
Je ne sais pas si c'est ici, mais tout le style est cassé au moins sur la page /collectivites-et-exploitants.

2024-08-06 03:55 UTC, martinratinaud commented on src/components/ui/Box.tsx
> -  xs: '320',
Super, merci, j'ai rajouté le xs manquant et un lien vers la doc des breakpoints DSFR

2024-08-06 03:56 UTC, martinratinaud commented on src/components/ui/Box.tsx
> +  ${({ theme, breakpoint }) => theme.media[breakpoint ?? 'lg']`
Good catch, effectivement, ici c'était un max-width au lieu d'un min-width. J'ai adapté le code

2024-08-06 09:02 UTC, totakoko approved these changes

2024-08-07 05:23 UTC, merged