Outil mesure distance
betagouv/france-chaleur-urbaine pull request #866
Opened 2024-09-17 15:14 UTC by totakoko

2024-09-18 11:12 UTC, martinratinaud reviewed
Après réflexion, je pense qu'il faut que nous édictions des règles claires quand à la décision du nommage en anglais ou français

Voila ma proposition:
- les parametres des urls en francais (car user facing)
- les noms métier restent en francais (Réseaux de froid, réseaux de chaleur,...)
- les noms facilement compréhensibles sont traduits en anglais (Outil devient Tool, Meesure devient Measure

Dis moi ce que tu en penses

2024-09-18 11:12 UTC, martinratinaud commented on src/hooks/useFCUMap.ts
> +  setMapRef: ReturnType<typeof useSetAtom<typeof mapRefAtom>>;
On peut utiliser ce Generic

`type SetAtom<T> = ReturnType<typeof useSetAtom<T>>;`

avec

```
type UseFCUMapResult = {
  setMapRef: SetAtom<typeof mapRefAtom>;
  setMapDraw: SetAtom<typeof mapDrawAtom>;
  setIsDrawing: SetAtom<typeof isDrawingAtom>;
} & (
  | { mapLoaded: false; mapRef: null; mapDraw: null; isDrawing: false }
  | {
      mapLoaded: true;
      mapRef: MapRef;
      mapDraw: MapboxDraw;
      isDrawing: boolean;
    }
);
```

2024-09-18 11:12 UTC, martinratinaud commented on src/components/Map/components/outils/mesure.ts
Si uniquement un fichier typescript, il peut etre appelé `mesure.d.ts`

2024-09-18 11:12 UTC, martinratinaud commented on src/components/Map/components/outils/OutilMesureDistances.tsx
> +function configureSourceAndLayers(map: Map) {
configure**s**SourceAndLayers vu qu'il ya plusieurs sources

2024-09-18 11:36 UTC, martinratinaud requested changes
Revu et super

Je mettrai les lignes un peu plus épaisses car difficilement visible en fonction des couleurs

2024-09-18 11:36 UTC, martinratinaud commented on src/components/Map/components/outils/MesureFeatureListItem.tsx
> +          <Colorful color={feature.properties.color} onChange={(color) => onColorUpdate(color.hex)} disableAlpha />
Possiblement remplacable par 

```
<input type="color" value={feature.properties.color} onChange={(event) => onColorUpdate(event.target.value)} />
 ```
 
 Mais si on ne souhaite pas IE 11 https://caniuse.com/input-color

2024-09-18 11:36 UTC, martinratinaud commented on src/components/Map/components/outils/mesure.ts
> +export type MesureFeature = GeoJSON.Feature<GeoJSON.LineString> & {
ici je mettrais donc MeasureFeature dans un fichier `tools/measure.d.ts`

2024-09-18 11:36 UTC, martinratinaud commented on src/components/Map/components/outils/OutilMesureDistances.tsx
> +function clearSourceAndLayers(map: Map) {
clearSource**s**AndLayers

2024-09-18 11:36 UTC, martinratinaud commented on src/components/Map/components/outils/OutilMesureDistances.tsx
> +    id: 'mesures-distances-lines',
J'appelerai cela `distance-measurement-lines`

2024-09-18 11:36 UTC, martinratinaud commented on src/components/Map/components/outils/OutilMesureDistances.tsx
> +    id: 'mesures-distances-labels',
J'appelerai cela `distance-measurement-labels`

2024-09-18 11:36 UTC, martinratinaud commented on src/components/Map/components/outils/OutilMesureDistances.tsx
> +export default OutilMesureDistances;
DistancesMeasurementTool

2024-09-18 11:36 UTC, martinratinaud commented on src/components/Map/components/outils/OutilMesureDistances.tsx
> +      if (featureBeingDrawn) {
use early exit `if (featureBeingDrawn) return`

2024-09-18 11:36 UTC, martinratinaud commented on src/components/Map/components/outils/OutilMesureDistances.tsx
> +          } else {
no need for else

2024-09-18 11:36 UTC, martinratinaud commented on src/components/Map/components/outils/OutilMesureDistances.tsx
> +    id: 'mesures-distances-lines',
et peut etre reutiliser linesSourceId

2024-09-18 11:57 UTC, totakoko reviewed
Merci pour les commentaires ! :)

2024-09-18 11:57 UTC, totakoko commented on src/components/Map/components/outils/OutilMesureDistances.tsx
> +function configureSourceAndLayers(map: Map) {
configureSourcesAndLayers plutôt. Oui bien vu !

2024-09-18 11:57 UTC, totakoko commented on src/components/Map/components/outils/mesure.ts
Oui c'est vrai, mais ça change vraiment qqch ? Un avantage là qui n'est pas exploité, c'est de pouvoir facilement mettre du code commun autre que les définitions typescript.
Je fais ça aussi car j'avais cru voir dans ce projet (sans doute un pb de conf), que le typage était moins bien vérifié dans les fichiers `.d.ts`

2024-09-18 11:57 UTC, totakoko commented on src/hooks/useFCUMap.ts
> +  setMapRef: ReturnType<typeof useSetAtom<typeof mapRefAtom>>;
J'ai regardé à nouveau côté jotai, mais rien. Donc j'ai utilisé ta proposition complétée pour que TS soit ok
```ts
type SetAtom<T extends WritableAtom<unknown, never[], unknown>> = ReturnType<typeof useSetAtom<T>>;
```

2024-09-18 11:57 UTC, totakoko commented on src/services/tiles.ts
> +// cacheAirtableTiles();
Tout à fait ! :sweat_smile: 

En fait pour chaque reload de l'appli, y'a un téléchargement des données airtable...

2024-09-18 14:51 UTC, totakoko commented
> Après réflexion, je pense qu'il faut que nous édictions des règles claires quand à la décision du nommage en anglais ou français
> 
> Voila ma proposition:
> 
> * les parametres des urls en francais (car user facing)
> * les noms métier restent en francais (Réseaux de froid, réseaux de chaleur,...)
> * les noms facilement compréhensibles sont traduits en anglais (Outil devient Tool, Meesure devient Measure
> 
> Dis moi ce que tu en penses

1. Oui pour les paramètres et URLs
2. Oui pour les noms métier
3. C'est plus compliqué pour savoir ce qui est facilement traduisible en anglais. Là on a donc maintenant DistancesMeasurementTool, et on va avoir DensitéThermiqueLinéaireTool ou bien LinearHeatDensityTool ?

2024-09-18 14:53 UTC, totakoko commented
> > Après réflexion, je pense qu'il faut que nous édictions des règles claires quand à la décision du nommage en anglais ou français
> > Voila ma proposition:
> > 
> > * les parametres des urls en francais (car user facing)
> > * les noms métier restent en francais (Réseaux de froid, réseaux de chaleur,...)
> > * les noms facilement compréhensibles sont traduits en anglais (Outil devient Tool, Meesure devient Measure
> > 
> > Dis moi ce que tu en penses
> 
> 1. Oui pour les paramètres et URLs
> 2. Oui pour les noms métier
> 3. C'est plus compliqué pour savoir ce qui est facilement traduisible en anglais. Là on a donc maintenant DistancesMeasurementTool, et on va avoir DensitéThermiqueLinéaireTool ou bien LinearHeatDensityTool ?

Et aussi, c'est pareil niveau commentaires, français ou anglais ? Je fais les 2 pour l'instant...

2024-09-19 05:19 UTC, martinratinaud approved these changes

2024-09-19 05:21 UTC, martinratinaud commented
Merci pour les changements, du coup je merge et on continue sur l'autre branche

2024-09-19 05:21 UTC, merged