Test d'adresse uniquement sur la fiche réseau, pas de villes
betagouv/france-chaleur-urbaine pull request #899
Opened 2024-10-16 08:44 UTC by totakoko

Par défaut le comportement de test d'adresse fonctionne comme ceci :
- On a une adresse globalement précise =>  l'utilisateur a la possibilité de laisser une demande
- On a une ville uniquement => on teste si la ville a un réseau de chaleur ou pas et on invite l'utilisateur à renseigner une adresse plus précise

Sur la fiche réseau, c'est une version différente (simplifiée) du test d'adresse (un peu différent aussi car on teste l'éligibilité avec un réseau en particulier), et on ne gérait pas le cas de test de ville.
Maintenant, le champ de recherche d'adresse ne retourne que des adresses précises. Je n'ai pas trouvé le moyen de juste exclure les villes...

Potentiellement il faudrait peut-être récupérer ces résultats classiquement, mais filtrer côté UI pour supprimer les suggestions de villes. :shrug: 
Je vais voir avec Florence pour valider ce point là.

2024-10-16 08:47 UTC, totakoko commented
![](https://github.trello.services/images/mini-trello-icon.png) [Réponse au test d'adresse sur les fiches par réseau](https://trello.com/c/DwXDiYSI/1309-r%C3%A9ponse-au-test-dadresse-sur-les-fiches-par-r%C3%A9seau)

2024-10-16 14:10 UTC, martinratinaud requested changes
Ok sur le principe, je pense qu'il serait plus judicieux de filtrer directement la requete

https://adresse.data.gouv.fr/api-doc/adresse

On peux ajouter `?type=street` par exemple

2024-10-16 14:12 UTC, totakoko commented
@martinratinaud  Alors j'avais fait ça juste avant avec housenumber (j'ai réécrasé mon commit), mais c'était trop précis. Y'avait pas moyen d'exclure, juste d'inclure un seul type... C'était pas bon pour Florence.

2024-10-16 14:14 UTC, totakoko commented
@martinratinaud cf https://github.com/betagouv/france-chaleur-urbaine/commit/1734da26

2024-10-17 09:03 UTC, martinratinaud approved these changes

2024-10-17 09:05 UTC, merged