Tracking Matomo des outils de la carte
betagouv/france-chaleur-urbaine pull request #934
Opened 2024-11-19 09:13 UTC by totakoko

Le tracking avait été un peu omis suite au refacto des outils.
Maintenant, globalement tous les boutons / actions importantes sont trackées.

2024-11-19 09:21 UTC, totakoko commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rétablir tracking des outils : définition d'une zone, calcul de densité thermique linéaire + ajout tracking mesure de distance](https://trello.com/c/C93k8hgl/1350-r%C3%A9tablir-tracking-des-outils-d%C3%A9finition-dune-zone-calcul-de-densit%C3%A9-thermique-lin%C3%A9aire-ajout-tracking-mesure-de-distance)

2024-11-20 08:40 UTC, martinratinaud requested changes

2024-11-20 08:40 UTC, martinratinaud commented on src/services/analytics.ts
> +  'Carto|Légende|Ouvre': {
Je vois pas cet éveènement utilisé ?

2024-11-20 08:40 UTC, martinratinaud commented on src/services/analytics.ts
> +  'Carto|Légende|Ferme': {
ni celui la

2024-11-20 08:42 UTC, totakoko commented on src/services/analytics.ts
> +  'Carto|Légende|Ouvre': {
En fait c'est dynamique, recherche `Carto|Légende|`. Je me suis fait avoir d'ailleurs dans un commit précédent...

2024-11-20 08:42 UTC, totakoko commented on src/services/analytics.ts
> +  'Carto|Légende|Ferme': {
Idem

2024-11-20 13:45 UTC, merged