Ajout feature admin pour tester en masse l'éligibilité de coordonnées
betagouv/france-chaleur-urbaine pull request #942
Opened 2024-11-21 10:26 UTC by totakoko

- Ajout d'une nouvelle page avec un outil pour tester un fichier CSV avec des coordonnées géographiques.
![image](https://github.com/user-attachments/assets/de78c31b-aee6-4d81-a2f7-deb371766efe)

- Le lien Admin se transforme en menu, pour que chaque outil soit rangé dans sa propre page. J'ai pas eu le courage de splitter l'actuelle page admin. Je me dis qu'il y aura des impacts avec les comptes pro à venir...

- C'est pour Camille qui a besoin périodiquement de traiter des fichiers sans adresses. Ca permettra de l'outiller un peu.

- J'ai fait le découpage CSV (ui) => json (api), afin d'obtenir une API plus classique en JSON. Même si pour le moment elle reste en /admin car un peu alpha quand même.

2024-11-22 07:00 UTC, martinratinaud requested changes
Testé avec ce fichier -> erreur `Error: failed to load data for /api/admin/bulk-eligibility-coordinates`

```csv
"longitude","latitude"
"48.856614","2.352222"
"48.864716","2.294350"
"48.851078","2.292127"
"48.866125","2.302127"
"48.858846","2.294350"
```

La meme en inversant longitude et latitude (j'avais fait une erreur)

Je serai d'avis de donner un fichier template à télécharger

2024-11-22 07:00 UTC, martinratinaud commented on src/pages/admin/test-coordonnees-geographiques.tsx
> +  const userSession = await getSession(context);
Je serai pour faire un HOC withPermission qui
- si pas de session, redirige vers /connexion
- si pas role passé en parametre, redirige vers /gestionnaire

2024-11-22 07:00 UTC, martinratinaud commented on src/pages/admin/test-coordonnees-geographiques.tsx
> +    if (!file) {
J'ai testé et si une erreur survient, le bouton reste dsiabled meme si on met un autre fichier

il faut je pense setCoordinates([]) à chaque "onFileChange"

2024-11-22 07:00 UTC, martinratinaud commented on src/pages/api/admin/bulk-eligibility-coordinates.ts
> +import { BadRequestError } from 'src/services/errors';
peut etre on pourrait le bouger direct dans @helpers/server

2024-11-25 08:42 UTC, totakoko reviewed
Merci pour tes commentaires, je vais apporter des correctifs.
Désolé pour le cas qui ne marche pas !
J'ai pas complètement géré les lignes foireuses, et du coup le schéma zod n'est pas content :grimacing: 
Je m'occupe de tout ça.

Pour le template, oui dans l'idéal, mais là c'était pour simplifier le travail des bizdev qui recoivent des fichiers avec plein de colonnes.

2024-11-25 08:42 UTC, totakoko commented on src/pages/admin/test-coordonnees-geographiques.tsx
> +  const userSession = await getSession(context);
Pour getServerSideProps, oui complètement. Là j'ai juste pompé ça d'une page authentifiée et c'est dupliqué.

Pour `si pas role passé en parametre, redirige vers /gestionnaire`, pas sûr de comprendre, mais on en parle tout à l'heure.

2024-11-25 08:42 UTC, totakoko commented on src/pages/api/admin/bulk-eligibility-coordinates.ts
> +import { BadRequestError } from 'src/services/errors';
Oui, :+1: 
Je l'avais mis à côté des ServiceError (mais qui semblent être plus frontend...)

2024-11-25 08:42 UTC, totakoko commented on src/pages/admin/test-coordonnees-geographiques.tsx
> +    if (!file) {
Oui t'as raison. Si y'a une erreur quelconque => setCoordinates([])

2024-11-25 16:02 UTC, totakoko commented
@martinratinaud J'ai apporté des corrections. J'ai viré les lignes avec erreurs et ça devrait fonctionner chez toi. Je fais valider avec Camille.

2024-11-26 09:52 UTC, martinratinaud approved these changes

2024-11-26 09:52 UTC, martinratinaud commented on src/helpers/ssr/withPermission.ts
> +export const withPermission = (role?: `${USER_ROLE}`): GetServerSideProps => {
on a besoin du template literal ici ?

2024-11-26 09:52 UTC, martinratinaud commented on src/helpers/ssr/withPermission.ts
> +          destination: '/connexion',
On peut faire

```
destination: `/connexion?notify=error:${encoreURIComponent("Vous devez être connecté pour accéder à cette page")}`,

2024-11-26 09:52 UTC, martinratinaud commented on src/helpers/ssr/withPermission.ts
> +import { GetServerSideProps } from 'next';
Si on passe le role, on devrait peut etre l'appeler `withRole`

2024-11-26 09:58 UTC, martinratinaud approved these changes

2024-11-26 09:58 UTC, martinratinaud commented on src/pages/admin/test-coordonnees-geographiques.tsx
> +          });
woaaaa, chatgpt? 🤩

2024-11-26 09:58 UTC, martinratinaud commented on src/pages/api/admin/bulk-eligibility-coordinates.ts
> +export const config = {
Que fait ce bout de code dans ce commit? je ne vois pas ou il est utilisé

2024-11-26 09:58 UTC, martinratinaud commented on src/core/notification.tsx
> +      captureException(err);
💪

2024-11-26 12:55 UTC, totakoko commented on src/pages/api/admin/bulk-eligibility-coordinates.ts
> +export const config = {
Bah c'est du next ! Pour lui dire que :
- pas besoin de warning si la réponse est > 4MO 
- augmenter la limite du body parser

2024-11-26 12:56 UTC, totakoko commented on src/pages/admin/test-coordonnees-geographiques.tsx
> +          });
Non pk ? :thinking:

2024-11-26 12:59 UTC, totakoko commented on src/helpers/ssr/withPermission.ts
> +export const withPermission = (role?: `${USER_ROLE}`): GetServerSideProps => {
Oui selon moi car avec typescript on a plus besoin des enums.
Je préfère utiliser `withPermission('admin')` plutôt que `withPermission(USER_ROLE.ADMIN)`.

Quel est ton avis ?

2024-11-26 13:03 UTC, totakoko commented on src/helpers/ssr/withPermission.ts
> +import { GetServerSideProps } from 'next';
Là je penserais plutôt à qqch genre requireAuthentication(role) ou ensureAuthentication(role). Ou bien withAuthentication.

2024-11-26 16:44 UTC, merged